name: Deploy Node.js App to PlanetHoster

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: workflow
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' 

    - name: Install dependencies
      run: |
        cd SiteWebFacilys
        npm ci

    - name: Create production .env file
      run: |
        cd SiteWebFacilys
        echo "NODE_ENV=production" > .env
        echo "PORT=passenger"  >> .env
        echo "HOST=127.0.0.1"  >> .env
        echo "FIREBASE_CONFIG=./facilys-fe686-firebase-adminsdk-2vciw-af78a9b08f.json"  >> .env
        echo "CSRF_SECRET=b7efd54a39e5e37c38177e1dcfbe25acf56ecc25c6443ed3308129dc41f8ed2f"  >> .env
        echo "PLANETHOSTER_API_KEY=891271ae8e70a8609d99a29ff23c0f76e1d817d952f7e1668e13ee56bb68aea8" >> .env
        echo "PLANETHOSTER_API_USER=d92ac0adc8f7ec4de7fd769af2f4d00b" >> .env
        echo "WORLDACCOUNTS=658763" >> .env

    - name: Copy SiteWebFacilys to temp directory
      run: |
        mkdir -p temp_deploy
        cp -R SiteWebFacilys/. temp_deploy/

    - name: Upload public/ to NOC S3 (PlanetHoster)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
        AWS_REGION: ht2-storage
        S3_ENDPOINT: https://ht2-storage.n0c.com:5443
        S3_BUCKET_NAME: jmaqmsnt
      run: |
        set -e
        set -x

        sudo apt-get update
        sudo apt-get install -y curl unzip

        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

        aws --version 

        export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
        export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
        export AWS_REGION="$AWS_REGION"

        aws configure set cli_pager ""

        aws --no-cli-pager s3 sync SiteWebFacilys/public s3://$S3_BUCKET_NAME/public/ \
        --endpoint-url "$S3_ENDPOINT" \
        --acl public-read \
        --delete

    - name: Cleaning folder to PlanetHoster
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd server
          find . -mindepth 1 -maxdepth 1 ! -name "passenger" ! -name ".git" -exec echo {} \;
          find . -mindepth 1 -maxdepth 1 ! -name "passenger" ! -name ".git" ! -name "src" -exec rm -rf {} \;
          exit

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "temp_deploy/."
        target: "server/"
        strip_components: 1

    - name: Deploy to PlanetHoster
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd server
          rm -f package-lock.json
          rm -rf node_modules
          source /home/jmaqmsnt/nodevenv/server/22/bin/activate
          npm install 
          npm install -g
          exit
