name: Deploy Blazor Server to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: "myprojectfacilys"
  SERVICE_NAME: "blazor-server-app"
  REGION: "europe-west1"
  ARTIFACT_REGISTRY: "europe-west1-docker.pkg.dev/myprojectfacilys/facilys-repo"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/403108519742/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions-deploy-2@myprojectfacilys.iam.gserviceaccount.com'

    - name: Setup Docker Auth
      run: |-
        gcloud auth configure-docker $REGION-docker.pkg.dev

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          ${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:latest

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        image: ${{ env.ARTIFACT_REGISTRY }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        region: ${{ env.REGION }}
        cpu: 1
        memory: 2Gi
        min_instances: 0
        max_instances: 5
        timeout: 300s
        ingress: all
        port: 8080
        allow_unauthenticated: true
        revision_suffix: ${{ github.sha }}
        labels: "managed-by=github-actions,commit-sha=${{ github.sha }}"

    - name: Ensure public access to Cloud Run
      run: |
        gcloud run services add-iam-policy-binding ${{ env.SERVICE_NAME }} \
          --region=${{ env.REGION }} \
          --project=${{ env.PROJECT_ID }} \
          --member="allUsers" \
          --role="roles/run.invoker"
